### PR TITLE
Home Church/Sunday Morning Map Fixes

### LINKED ISSUE #478: Find a Home Church loading box
Can we make some changes?

* [x] Keep "loading home church listings" at the top with the loading animation
* [x] Get rid of the grey box
* [x] List sites in pill shape
* [x] Make sites clickable so only HCs for that site load (until user makes a selection, load can be as is)
* [x] Remove the sites drop down and postal code field
* [x] Add a day of the week dropdown

### LINKED ISSUE #598: Find a Home Church Module Update
Can we make the location popups in the map for find a home church and find a location match the design found here: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=773%3A10839

Basically, the colours should be inverted - black background and white text.

@deeinstereo assuming this is still wanted?

### PR DESCRIPTION
**Pull request by itbel**
- HomeChurch map pop-up figma design implemented
- Pop-ups now show up at appropriate coordinates
resolves #598,  resolves #478

### CODE REVIEW

File: src/components/RenderRouter/HomeChurchItem.tsx [hunk 1]
```diff
@@ -550,22 +555,39 @@ export class ContentItem extends React.Component<Props, State> {
...
+                      this.state.selectedPlace?.location?.address
+                        ?.latitude as string
+                    ) as number,
+                    lng: parseFloat(
+                      this.state.selectedPlace?.location?.address
+                        ?.longitude as string
+                    ) as number,
+                  }}
+                  visible={
+                    this.state.selectedPlace || this.state.selectedPlaceMarker
```
Comment (JonEsparaz) [inline src/components/RenderRouter/HomeChurchItem.tsx:574]: This is the same as:
```javascript
Boolean(this.state.selectedPlace || this.state.selectedPlaceMarker)
```

Or you can double bang:
```javascript
!!(this.state.selectedPlace || this.state.selectedPlaceMarker)
```

File: src/components/RenderRouter/SundayMorningItem.tsx [hunk 2]
```diff
@@ -379,13 +380,25 @@ export class SundayMorningItem extends React.Component<Props, State> {
...
                       }
-                      visible={true}
+                      position={{
+                        lat: this.state.selectedPlace?.location
+                          .latitude as number,
+                        lng: this.state.selectedPlace?.location
+                          .longitude as number,
+                      }}
+                      visible={
+                        this.state.selectedPlace ||
```
Comment (JonEsparaz) [inline src/components/RenderRouter/SundayMorningItem.tsx:397]: Same feedback as above.

**Comment by itbel** [comment]
Thanks! @JonEsparaz
